package nutrisync.flashpage;



import java.io.IOException;
import javax.media.Manager;
import javax.media.Player;
import java.io.File;
import hib.beans.Doctor;
import hib.beans.Patient;
import java.awt.Color;
import java.net.MalformedURLException;
import java.text.DateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.CannotRealizeException;
import javax.media.NoPlayerException;
import javax.swing.JOptionPane;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import spr.hib.dao.LogicalCodeDAO;

public class DoctorDashboard extends javax.swing.JFrame {

    /**
     * Creates new form DoctorDashboard
     */
    public DoctorDashboard() {
        initComponents();
        Date date=new Date();
        DateFormat df=DateFormat.getDateInstance(DateFormat.FULL);
        jLabel8.setText(df.format(date));
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("COPYRIGHTS @2025 NUTRISYNC PVT LTD                                                                                                                                                                   ALL RIGHTS RESERVED");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 760, 20));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 770, 20));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 51, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 255, 255));
        jButton4.setText("L O A D");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 160, 30));

        jPanel15.setBackground(new java.awt.Color(204, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 0, 204));
        jPanel15.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 200, 40));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 0, 204));
        jPanel15.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 40));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel15.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 200, 40));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(51, 0, 204));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel15.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 200, 40));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(51, 0, 204));
        jPanel15.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 200, 40));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(51, 0, 204));
        jPanel15.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 200, 40));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(51, 0, 204));
        jPanel15.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 200, 40));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(51, 0, 204));
        jPanel15.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 200, 40));

        jPanel7.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 490, 240));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 540, 290));

        jTabbedPane1.addTab("ACCOUNT", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(204, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(51, 102, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/med.png"))); // NOI18N
        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 110));

        jButton2.setBackground(new java.awt.Color(204, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 0, 153));
        jButton2.setText("ORDER MEDICINES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 137, 140, 40));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 160, 200));

        jPanel13.setBackground(new java.awt.Color(0, 102, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/food.png"))); // NOI18N
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 120));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setText("ORDER FOOD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 140, 140, 40));

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 160, 200));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 550, 300));

        jTabbedPane1.addTab("ADD ORDER +", jPanel3);

        jPanel8.setBackground(new java.awt.Color(51, 153, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBackground(new java.awt.Color(102, 204, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setForeground(new java.awt.Color(51, 153, 255));
        jPanel14.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 220, 40));

        jTextField3.setEditable(false);
        jTextField3.setForeground(new java.awt.Color(51, 153, 255));
        jPanel14.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 40));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(51, 153, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel14.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 480, 110));

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 530, 220));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 102, 204));
        jTextField1.setText("ENTER PATIENT ID TO VIEW REPORT");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 250, 40));

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setText("L O A D");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 20));

        jPanel8.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 550, 300));

        jTabbedPane1.addTab("VIEW REPORTS", jPanel8);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(0, 0, 102));
        jPanel17.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/music_2.gif"))); // NOI18N
        jPanel17.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 200, 110));

        jPanel18.setBackground(new java.awt.Color(102, 102, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(153, 153, 255)));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(102, 102, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 153));
        jButton6.setText("PAUSE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        jPanel18.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 80, 30));
        jPanel20.setVisible(false);

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 153));
        jButton5.setText("PLAY");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 60, -1));

        jButton7.setBackground(new java.awt.Color(204, 255, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 153));
        jButton7.setText("NEXT");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 60, -1));

        jButton8.setBackground(new java.awt.Color(204, 255, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 153));
        jButton8.setText("PREV");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, -1));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 240, 60));

        jPanel19.setBackground(new java.awt.Color(153, 153, 255));
        jPanel17.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 240, 130));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 380, 230));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/doctorDashboard_1.gif"))); // NOI18N
        jPanel16.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 330));

        jTabbedPane1.addTab("CJ's DJ", jPanel16);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 690, 330));

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("WELCOME !!");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 266, 90, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/doctorIconbg.png"))); // NOI18N
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 100, 90));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 130, 330));

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 102, 102));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/theme_1.png"))); // NOI18N
        jToggleButton1.setSelected(true);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 30, 30));
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 30, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 0, 190, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logout.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, 30));

        jComboBox4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(0, 0, 204));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------     QUICK LINKS     ------" }));
        jComboBox4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 153)));
        jPanel6.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 200, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/settings.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/info.png"))); // NOI18N
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 30, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/clock_1.png"))); // NOI18N
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 30, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/doctorDashboard_1.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 770, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 420));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 204));
        jMenuBar1.setForeground(new java.awt.Color(204, 255, 255));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("PROFILE");

        jMenuItem1.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem1.setText("EDIT PROFILE");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setForeground(new java.awt.Color(51, 51, 255));
        jMenuItem2.setText("ABOUT");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setForeground(new java.awt.Color(51, 51, 255));
        jMenuItem3.setText("SETTINGS");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem4.setText("LOG-OUT");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked

    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    this.dispose();
    new Login().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        if(!jToggleButton1.isSelected())
        {
            jMenuBar1.setBackground(Color.black);
            jMenuBar1.setForeground(Color.white);
            jPanel2.setBackground(Color.black);
            jPanel6.setBackground(Color.black);
            jPanel9.setBackground(Color.black);
            jPanel10.setBackground(Color.black);
            jTabbedPane1.setBackground(Color.black);
            jLabel6.setForeground(Color.white);
            jTabbedPane1.setForeground(Color.blue);
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/darkDoctor.gif")));
            jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/theme1.png")));
        }
        if(jToggleButton1.isSelected())
        {
            jPanel9.setBackground(new java.awt.Color(204,255,255));
            jMenuBar1.setBackground(Color.blue);
            jPanel2.setBackground(new java.awt.Color(204,255,255));
            jPanel6.setBackground(new java.awt.Color(204,255,255));
            jPanel10.setBackground(new java.awt.Color(204,255,255));
            jMenuBar1.setForeground(new java.awt.Color(204,255,255));
            jTabbedPane1.setBackground(new java.awt.Color(204,255,255));
            jTabbedPane1.setForeground(Color.blue);
            jLabel6.setForeground(Color.blue);
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/doctorDashboard_1.gif")));
            jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/theme_1.png")));
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new PharmacyFlash().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new RestroFlash().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
       jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    String id =jTextField1.getText();
    ApplicationContext context=new ClassPathXmlApplicationContext("/SpringXMLConfig.xml");
    LogicalCodeDAO dao=(LogicalCodeDAO)context.getBean("techno");
    List<Patient> list=dao.getProfileInfoPatient(id);
    for(Patient data:list){
        jTextArea1.setText(data.getDescription());
        jTextField2.setText(data.getAilment());
        jTextField3.setText(data.getFullName());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String id=Login.id1;
        ApplicationContext context=new ClassPathXmlApplicationContext("/SpringXMLConfig.xml");
        LogicalCodeDAO dao=(LogicalCodeDAO)context.getBean("techno");
        List<Doctor> list=dao.getProfileInfoDoctor(id);
        for(Doctor data:list){
            jTextField5.setText(data.getFullName());
            jTextField6.setText(data.getEmailId());
            jTextField7.setText(data.getExperience());
            jTextField8.setText(data.getQualification());
            jTextField9.setText(data.getPost());
            jTextField10.setText(data.getGender());
            jTextField4.setText(data.getdOB());
            jTextArea2.setText(data.getAddress());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     jPanel20.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    jPanel20.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

    }//GEN-LAST:event_jButton8ActionPerformed
    int COUNT=0;
    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        COUNT++;
        String audio[]={"D:\\FSJ\\NutriSync\\src\\media\\Aafat.wav","D:\\FSJ\\NutriSync\\src\\media\\aud.wav","D:\\FSJ\\NutriSync\\src\\media\\hrg.wav","D:\\FSJ\\NutriSync\\src\\media\\Backbone.wav","D:\\FSJ\\NutriSync\\src\\media\\Badshah.wav","D:\\FSJ\\NutriSync\\src\\media\\Faayah.wav","D:\\FSJ\\NutriSync\\src\\media\\Ghungroo.wav","D:\\FSJ\\NutriSync\\src\\media\\Ekdin.wav","D:\\FSJ\\NutriSync\\src\\media\\Basti.wav","D:\\FSJ\\NutriSync\\src\\media\\Bijli.wav","D:\\FSJ\\NutriSync\\src\\media\\Billi.wav","D:\\FSJ\\NutriSync\\src\\media\\GR.wav","D:\\FSJ\\NutriSync\\src\\media\\heerRanjha.wav","D:\\FSJ\\NutriSync\\src\\media\\dilGalti.wav","D:\\FSJ\\NutriSync\\src\\media\\gatiwidhi.wav","D:\\FSJ\\NutriSync\\src\\media\\cgs.wav","D:\\FSJ\\NutriSync\\src\\media\\DJKhalid.wav","D:\\FSJ\\NutriSync\\src\\media\\Excuses.wav","D:\\FSJ\\NutriSync\\src\\media\\Fl.wav","D:\\FSJ\\NutriSync\\src\\media\\Bezubaan.wav","D:\\FSJ\\NutriSync\\src\\media\\Eye.wav","D:\\FSJ\\NutriSync\\src\\media\\EHN.wav","D:\\FSJ\\NutriSync\\src\\media\\EB.wav","D:\\FSJ\\NutriSync\\src\\media\\danceKaBhoot.wav","D:\\FSJ\\NutriSync\\src\\media\\Doobey.wav","D:\\FSJ\\NutriSync\\src\\media\\Coca.wav","D:\\FSJ\\NutriSync\\src\\media\\Currentlaga.wav","D:\\FSJ\\NutriSync\\src\\media\\Coca2.wav","D:\\FSJ\\NutriSync\\src\\media\\chunari.wav","D:\\FSJ\\NutriSync\\src\\media\\danceMeri.wav","D:\\FSJ\\NutriSync\\src\\media\\Chakachak.wav","D:\\FSJ\\NutriSync\\src\\media\\EV.wav","D:\\FSJ\\NutriSync\\src\\media\\Energy.wav"};
        for (int i=COUNT;i<audio.length;i++) {
            
            try {
            Player play1= Manager.createRealizedPlayer(new File(audio[i]).toURI().toURL());
            play1.start();
            JOptionPane.showMessageDialog(null,"NEXT>>");
            play1.stop();
            } catch (MalformedURLException ex) {
            } catch (IOException | NoPlayerException | CannotRealizeException ex) {
              
            }
        }

    }//GEN-LAST:event_jButton7MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked

    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
    String audio[]={"D:\\FSJ\\NutriSync\\src\\media\\Aafat.wav","D:\\FSJ\\NutriSync\\src\\media\\aud.wav","D:\\FSJ\\NutriSync\\src\\media\\hrg.wav","D:\\FSJ\\NutriSync\\src\\media\\Backbone.wav","D:\\FSJ\\NutriSync\\src\\media\\Badshah.wav","D:\\FSJ\\NutriSync\\src\\media\\Faayah.wav","D:\\FSJ\\NutriSync\\src\\media\\Ghungroo.wav","D:\\FSJ\\NutriSync\\src\\media\\Ekdin.wav","D:\\FSJ\\NutriSync\\src\\media\\Basti.wav","D:\\FSJ\\NutriSync\\src\\media\\Bijli.wav","D:\\FSJ\\NutriSync\\src\\media\\Billi.wav","D:\\FSJ\\NutriSync\\src\\media\\GR.wav","D:\\FSJ\\NutriSync\\src\\media\\heerRanjha.wav","D:\\FSJ\\NutriSync\\src\\media\\dilGalti.wav","D:\\FSJ\\NutriSync\\src\\media\\gatiwidhi.wav","D:\\FSJ\\NutriSync\\src\\media\\cgs.wav","D:\\FSJ\\NutriSync\\src\\media\\DJKhalid.wav","D:\\FSJ\\NutriSync\\src\\media\\Excuses.wav","D:\\FSJ\\NutriSync\\src\\media\\Fl.wav","D:\\FSJ\\NutriSync\\src\\media\\Bezubaan.wav","D:\\FSJ\\NutriSync\\src\\media\\Eye.wav","D:\\FSJ\\NutriSync\\src\\media\\EHN.wav","D:\\FSJ\\NutriSync\\src\\media\\EB.wav","D:\\FSJ\\NutriSync\\src\\media\\danceKaBhoot.wav","D:\\FSJ\\NutriSync\\src\\media\\Doobey.wav","D:\\FSJ\\NutriSync\\src\\media\\Coca.wav","D:\\FSJ\\NutriSync\\src\\media\\Currentlaga.wav","D:\\FSJ\\NutriSync\\src\\media\\Coca2.wav","D:\\FSJ\\NutriSync\\src\\media\\chunari.wav","D:\\FSJ\\NutriSync\\src\\media\\danceMeri.wav","D:\\FSJ\\NutriSync\\src\\media\\Chakachak.wav","D:\\FSJ\\NutriSync\\src\\media\\EV.wav","D:\\FSJ\\NutriSync\\src\\media\\Energy.wav"};
    for (int i=audio.length-1;i>=0;i--)
    {
	Player play1;
        try {
        play1 = Manager.createRealizedPlayer(new File(audio[i]).toURI().toURL());
        play1.start();
	JOptionPane.showMessageDialog(null,"<<PREV");
        play1.stop();
        } catch (MalformedURLException ex) {
        } catch (IOException | NoPlayerException | CannotRealizeException ex) {
        }
    }
    }//GEN-LAST:event_jButton8MouseClicked

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DoctorDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
