package nutrisync.flashpage;
import javax.media.Manager;
import javax.media.Player;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import javax.media.CannotRealizeException;
import javax.media.NoPlayerException;


public class RestroFlash extends javax.swing.JFrame implements Runnable{
    @SuppressWarnings("CallToThreadStartDuringObjectConstruction")
    public RestroFlash() 
    {
        initComponents();
        Thread thread=new Thread(this);
        thread.start();
    }
    @Override
    @SuppressWarnings("SleepWhileInLoop")
    public void run()
    {
        try
        {
            String mess[]={"Loading Module","Loading Module","Please Wait.","Please Wait..","Please Wait...","Please Wait....","Please Wait.","Please Wait..","Please Wait...","Please Wait....","YUMM !!"};
            int k=0;
            Player play=Manager.createRealizedPlayer(new File("D:\\FSJ\\NutriSync\\src\\media\\aud.wav").toURI().toURL());
            play.start();
        for(int i=jProgressBar1.getMinimum();i<=jProgressBar1.getMaximum();i++)
        {
            int j=i;
            jProgressBar1.setValue(i);
            jLabel2.setText(i+"%");
            Thread.sleep(50);
            if(j%10==0)
            {
                jLabel3.setText(mess[k]);
//                jLabel3.setForeground(new Color(red,green,blue));
                k++;
            }
        }
        play.stop();
        new CanteenDashboard().setVisible(true);
        this.dispose();
        }catch(InterruptedException | MalformedURLException ex){} catch (IOException | NoPlayerException | CannotRealizeException ex) {  
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 110, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 40, 20));

        jProgressBar1.setBackground(new java.awt.Color(0, 0, 0));
        jProgressBar1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 290, 510, 10));

        jLabel1.setBackground(new java.awt.Color(153, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/cjrestro.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable(){
            @Override
            public void run() {
                new RestroFlash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
